---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: ping
      ping:
    
    - name: swap the slot with production slot
      azure_rm_webapp_slot:
        resource_group: "tutorial01"
        webapp_name: "tutorial-app01-staging"
        name: "staging"
        swap:
          action: swap  