- hosts: local
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        resource_group: tutorial01
        name: tutorial01
        template:
          $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
          contentVersion: "1.0.0.0"
          variables:
            container1name: "hellofiles"
            container1image: "mcr.microsoft.com/azuredocs/aci-hellofiles"
          resources:
            name: "file-share-demo"
            type: "Microsoft.ContainerInstance/containerGroups"
            apiVersion: "2018-10-01"
            location: "[resourceGroup().location]"
            properties:
              containers:
                - name: "[variables('container1name')]"
                  properties:
                    image: "[variables('container1image')]"
                    resources:
                      requests:
                        cpu: 1
                        memoryInGb: 1.5
                  ports:
                    port:
                  volumeMounts:
                    name: "filesharevolume"
                    mountPath: "/aci/logs"
              osType: "Linux"
              ipAddress:
                type: "Public"
                ports:
                  - protocol: "tcp"
                    port: 80
                dnsNameLabel: "aci-demo"
              volumes:
                - name: "filesharevolume"
                  azureFile:
                    shareName: "acishare"
                    storageAccountName: "<Storage account name>"
                    storageAccountKey: "<Storage account key>"