---
localhost:
  hosts:
    localhost:
      ansible_connection: local
  vars:
    ansible_python_interpreter: /Users/samitkumarpatel/other/azure/ansible/.venv/bin/python3
controller:
  hosts:
    168.63.9.118
  vars:
    ansible_password: lab_admin123
    ansible_python_interpreter: /bin/python
swarm-master:
  hosts:
    10.10.1.4
  vars:
    ansible_user: lab_admin
    ansible_password: lab_admin123
swarm-worker:
  hosts:
    10.10.1.5
  vars:
    ansible_user: lab_admin
    ansible_password: lab_admin123
swarm:
  children:
    swarm-master:
    swarm-worker: