---
- hosts: swarm
  become: true
  handlers:
  - name: upgrade yum
    yum:
      name: '*'
      state: latest
    listen: "update"
  tasks:
  - name: install basic package for centos
    include_tasks: centos-package.yml